/*
 * Iris is a World Generator for Minecraft Bukkit Servers
 * Copyright (c) 2022 Arcane Arts (Volmit Software)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package art.arcane.iris.engine.object;

import art.arcane.iris.core.loader.IrisRegistrant;
import art.arcane.iris.engine.object.annotations.ArrayType;
import art.arcane.iris.engine.object.annotations.Desc;
import art.arcane.iris.engine.object.annotations.MaxNumber;
import art.arcane.iris.engine.object.annotations.MinNumber;
import art.arcane.iris.engine.object.annotations.RegistryListResource;
import art.arcane.iris.engine.object.annotations.Required;
import art.arcane.volmlib.util.collection.KList;
import art.arcane.volmlib.util.json.JSONObject;
import art.arcane.iris.util.common.plugin.VolmitSender;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Desc("A jigsaw structure. Starting from a pool, the assembler places a start piece and recursively attaches more pieces through matching connectors until it reaches the max depth or size. Pieces are Iris objects, so they carry the full object placement and block-control feature set.")
@Data
@EqualsAndHashCode(callSuper = false)
public class IrisStructure extends IrisRegistrant {
    @Required
    @RegistryListResource(IrisJigsawPool.class)
    @Desc("The pool the assembler draws the start piece from.")
    private String startPool = "";

    @MinNumber(1)
    @MaxNumber(30)
    @Desc("The maximum jigsaw recursion depth. Larger values allow larger structures (e.g. villages) at the cost of generation time.")
    private int maxDepth = 7;

    @MinNumber(1)
    @MaxNumber(32)
    @Desc("The maximum radius of the structure in chunks from its start piece. Acts as a hard bound on assembly size and collision checks.")
    private int maxSizeChunks = 8;

    @Desc("The place mode used when stamping each piece object into the world.")
    private ObjectPlaceMode placeMode = ObjectPlaceMode.STRUCTURE_PIECE;

    @ArrayType(min = 1, type = IrisObjectReplace.class)
    @Desc("Find-and-replace block edits applied to every piece of this structure, using the exact same syntax as an object's 'edit'. For example, replace stone bricks with obsidian.")
    private KList<IrisObjectReplace> edit = new KList<>();

    @ArrayType(type = String.class, min = 1)
    @RegistryListResource(IrisLootTable.class)
    @Desc("Loot tables applied to containers placed by this structure's pieces.")
    private KList<String> loot = new KList<>();

    @Desc("If this structure was generated by importing a vanilla or datapack structure, this is that structure's key (provenance). Empty for hand-authored structures.")
    private String vanillaSource = "";

    @Override
    public String getFolderName() {
        return "structures";
    }

    @Override
    public String getTypeName() {
        return "Structure";
    }

    @Override
    public void scanForErrors(JSONObject p, VolmitSender sender) {

    }
}
